import { useState } from "react";
import axios from "axios";
import ScoreBreakdown from "./ScoreBreakdown";
import jsPDF from "jspdf";

function App() {
  const [username, setUsername] = useState("");
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const analyzeProfile = async () => {
    if (!username) return;
    setLoading(true);
    setData(null);
    setError("");

    try {
      const res = await axios.get(
  `https://repolens-ai-r10q.onrender.com/api/github/${encodeURIComponent(username)}`
);


      setData(res.data);
    } catch {
      setError("User not found. Please check the username and try again.");
    }

    setLoading(false);
  };

  const downloadPDF = () => {
    if (!data) return;

    const doc = new jsPDF();

    doc.setFillColor(21, 23, 61);
    doc.rect(0, 0, 210, 30, "F");
    doc.setTextColor(241, 233, 233);
    doc.setFontSize(18);
    doc.text("RepoLens AI - GitHub Portfolio Report", 14, 18);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.text(`Name: ${data.name || data.username}`, 14, 45);
    doc.text(`GitHub Username: ${data.username}`, 14, 52);
    doc.text(`Followers: ${data.followers}`, 14, 59);

    doc.setFillColor(233, 145, 201);
    doc.rect(140, 40, 50, 25, "F");
    doc.setFontSize(16);
    doc.setTextColor(21, 23, 61);
    doc.text(`${data.score}/100`, 165, 56, { align: "center" });

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text("Recruiter Summary", 14, 75);
    doc.line(14, 78, 196, 78);
    doc.setFontSize(11);
    doc.text(doc.splitTextToSize(data.summary, 180), 14, 86);

    let y = 110;

    doc.setFontSize(14);
    doc.text("Strengths", 14, y);
    doc.line(14, y + 2, 196, y + 2);
    y += 10;

    doc.setFontSize(11);
    data.strengths.forEach(s => {
      doc.text(`- ${s}`, 18, y);
      y += 7;
    });

    y += 5;

    doc.setFontSize(14);
    doc.text("Areas to Improve", 14, y);
    doc.line(14, y + 2, 196, y + 2);
    y += 10;

    doc.setFontSize(11);
    data.improvements.forEach(i => {
      doc.text(`- ${i}`, 18, y);
      y += 7;
    });

    y += 5;

    doc.setFontSize(14);
    doc.text("Top Projects", 14, y);
    doc.line(14, y + 2, 196, y + 2);
    y += 10;

    doc.setFontSize(11);
    data.topProjects.forEach(repo => {
      const repoLine = `${repo.name}  |  Stars: ${repo.stars}`;
      doc.text(repoLine, 18, y);
      y += 7;

      if (repo.description) {
        const descLines = doc.splitTextToSize(repo.description, 160);
        doc.setFontSize(10);
        doc.text(descLines, 22, y);
        y += descLines.length * 5 + 2;
        doc.setFontSize(11);
      }
    });

    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text("Generated by RepoLens AI", 14, 285);

    doc.save(`${data.username}_RepoLens_Report.pdf`);
  };

  return (
    <div style={styles.page}>
      <div style={styles.container}>
        <h1 style={styles.title}>RepoLens AI</h1>
        <p style={styles.subtitle}>AI-powered GitHub portfolio evaluation</p>

        <div style={styles.searchBox}>
          <input
            type="text"
            placeholder="Enter GitHub profile URL"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            style={styles.input}
          />
          <button onClick={analyzeProfile} style={styles.button}>Analyze</button>
        </div>

        {loading && (
          <div style={styles.loaderWrapper}>
            <div style={styles.loader}></div>
          </div>
        )}

        {error && <div style={styles.errorBox}>{error}</div>}

        {data && (
          <>
            <div style={styles.profileCard}>
              <img src={data.avatar} alt="avatar" style={styles.avatar}/>
              <div>
                <h2>{data.name || data.username}</h2>
                <p>{data.bio}</p>
                <p>👥 {data.followers} followers</p>
              </div>
            </div>

            <div style={styles.dashboard}>
              <div style={styles.glassCard}>
                <h2>Portfolio Score</h2>
                <div style={styles.score}>{data.score}/100</div>
                <p>Active Repositories (last 6 months): {data.activeRepos}</p>

                <button onClick={downloadPDF} style={styles.downloadBtn}>
                  Download PDF Report
                </button>
              </div>

              <div style={styles.glassCard}>
                <h3>Recruiter Summary</h3>
                <p>{data.summary}</p>
              </div>

              <div style={styles.glassCard}>
                <h3>Strengths</h3>
                <ul>{data.strengths.map((s, i) => <li key={i}>{s}</li>)}</ul>
              </div>

              <div style={styles.glassCard}>
                <h3>Improvements</h3>
                <ul>{data.improvements.map((i, idx) => <li key={idx}>{i}</li>)}</ul>
              </div>

              <div style={styles.glassCard}>
                <h3>Top Projects</h3>
                {data.topProjects.map((repo, i) => (
                  <div key={i} style={styles.repoItem}>
                    <b>{repo.name}</b> | Stars: {repo.stars}
                    <p>{repo.description}</p>
                  </div>
                ))}
              </div>

              <div style={styles.glassCard}>
                <h3 style={{ textAlign: "center" }}>Score Breakdown</h3>
                <ScoreBreakdown breakdown={data.breakdown} />
              </div>
            </div>
          </>
        )}

        <div style={styles.footer}>
          <p style={styles.footerText}>Created by Srija Chinthakunta</p>
          <div style={styles.iconRow}>
            <a href="https://linkedin.com/in/srija-chinthakunta-932ba3317" target="_blank" rel="noreferrer">
              <img src="https://cdn-icons-png.flaticon.com/512/174/174857.png" alt="LinkedIn" style={styles.icon}/>
            </a>
            <a href="https://github.com/SrijaChinthakunta" target="_blank" rel="noreferrer">
              <img src="https://cdn-icons-png.flaticon.com/512/733/733553.png" alt="GitHub" style={styles.icon}/>
            </a>
            <a href="mailto:chinthakuntasrija1@gmail.com">
              <img src="https://cdn-icons-png.flaticon.com/512/732/732200.png" alt="Email" style={styles.icon}/>
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}

const styles = {
  page:{minHeight:"100vh",background:"linear-gradient(135deg,#15173D,#982598)",display:"flex",justifyContent:"center",padding:"40px",fontFamily:"Segoe UI"},
  container:{width:"100%",maxWidth:"950px",color:"#F1E9E9"},
  title:{textAlign:"center",fontSize:"36px"},
  subtitle:{textAlign:"center",opacity:0.8,marginBottom:"20px"},
  searchBox:{textAlign:"center",marginBottom:"20px"},
  input:{padding:"12px",width:"260px",borderRadius:"8px",border:"none",marginRight:"10px"},
  button:{padding:"12px 18px",borderRadius:"8px",border:"none",background:"#E491C9",color:"#15173D",fontWeight:"bold"},
  downloadBtn:{marginTop:"15px",padding:"10px 16px",borderRadius:"8px",border:"none",background:"#E491C9",color:"#15173D",fontWeight:"bold",cursor:"pointer"},
  loaderWrapper:{display:"flex",justifyContent:"center",marginTop:"10px"},
  loader:{border:"4px solid rgba(255,255,255,0.2)",borderTop:"4px solid #E491C9",borderRadius:"50%",width:"28px",height:"28px",animation:"spin 1s linear infinite"},
  errorBox:{marginTop:"10px",background:"rgba(255,0,0,0.1)",border:"1px solid rgba(255,0,0,0.4)",color:"#ffb3b3",padding:"10px",borderRadius:"8px",textAlign:"center"},
  profileCard:{display:"flex",gap:"20px",alignItems:"center",background:"rgba(241,233,233,0.1)",padding:"20px",borderRadius:"14px",marginBottom:"20px",backdropFilter:"blur(12px)"},
  avatar:{width:"90px",borderRadius:"50%"},
  dashboard:{display:"grid",gap:"20px"},
  glassCard:{background:"rgba(241,233,233,0.1)",borderRadius:"14px",padding:"20px",backdropFilter:"blur(12px)"},
  score:{fontSize:"34px",fontWeight:"bold",color:"#E491C9"},
  repoItem:{marginBottom:"12px",padding:"12px",background:"rgba(241,233,233,0.12)",borderRadius:"10px",border:"1px solid rgba(255,255,255,0.08)"},
  footer:{textAlign:"center",marginTop:"35px"},
  footerText:{marginBottom:"10px",fontSize:"14px",opacity:0.85},
  iconRow:{display:"flex",justifyContent:"center",gap:"18px"},
  icon:{width:"28px",height:"28px",filter:"brightness(0) invert(1)"}
};

const styleSheet = document.styleSheets[0];
styleSheet.insertRule(`@keyframes spin {0%{transform:rotate(0deg);}100%{transform:rotate(360deg);}}`, styleSheet.cssRules.length);

export default App;
